### ISSUE TITLE
Recommend gt and kableExtra

### ISSUE THREAD

**Issue by JiaxiangBU** [pzhaonet/rmd#2]
Hi @pzhaonet , I read your [post](https://www.pzhao.org/zh/post/rmd/), 
I recommend gt and kableExtra, the two package in your list.

1. gt, although its status is not official, it hosted by RStudio on Github. This package like ggplot2, displays table in an elegant way.
1.  kableExtra is another package (like knitr plus) to helps R(Markdown) users to displays table. It is official on the R-CRAN by several versions.

**Comment by pzhaonet** [comment]
Added to the list. Thank you very much for your recommendation.
